# Generated by Django 4.2.7 on 2023-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_alter_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'disponible'), ('DISPONIBLE', 'DISPONIBLE'), ('no disponible', 'no disponible'), ('NO DISPONIBLE', 'NO DISPONIBLE')], default=True, max_length=20),
        ),
    ]
