# Generated by Django 4.2.7 on 2023-12-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_alter_libro_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='rating',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'disponible'), ('no disponible', 'no disponible')], default=True, max_length=20),
        ),
    ]
